### ISSUE TITLE
Stuck at executing Power Shell Scripts

### ISSUE THREAD

**Issue by cykie** [Microsoft/r-server-fraud-detection#10]
I have encountered issues while trying to execute the power shell scripts. It pops up some errors.
Not able to even install the import-module.
I have attached the log. Appreciate if someone could help!! 

PS>TerminatingError(Import-Module): "Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automation, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'."
Import-Module : Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automation, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
At C:\SetupVM.ps1:52 char:5
[setup_log.txt](https://github.com/Microsoft/r-server-fraud-detection/files/1832963/setup_log.txt)

**Comment by sdgilley** [comment]
Thanks, we're looking at this now, will let you know when we have it fixed!

**Comment by v-robwhi** [comment]
I was able to find the issue this afternoon and rectify it. GO ahead and try it again

**Comment by cykie** [comment]
Hi v-robwhi,
Thanks for your prompt reply.
I tried to re-run the \.SetupVM.ps1 but still face the same issues in the log. I have attached the new log again.
[setup_log.txt](https://github.com/Microsoft/r-server-fraud-detection/files/1840428/setup_log.txt)

Besides, I also downloaded a new SetupVM.ps1 and it's showing me some different message as below when I using power shell:
.\SetupVM.ps1 : File C:\SetupVM.ps1 cannot be loaded. The file C:\SetupVM.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\SetupVM.ps1
+ ~~~~~~~~~~~~~
+ CategoryInfo          : SecurityError: (:) [], PSSecurityException
+ FullyQualifiedErrorId : UnauthorizedAccess


Could you kindly let me know if I am doing the wrong way?
And I am not too sure what to input as username, password and prompt when executing the original SetupVM.ps1.

Thank you and appreciate your help!

**Comment by v-robwhi** [comment]
ok , few things , you need to change your execution policy for power shell. To do that you will need to run the command Set-Executionpolicy with the switch that is appropriate for your network. You can follow that link that you sent to learn about the policies. I am not sure which OS you are using but if it is not a Server SKU you will need to call the SetUpVM.ps1 file from an elevated powershell window. As for the user name and password , you can use anything you want. It creates a SQL Server User (as opposed to a windows user) that the sample web report uses to connect to SQL. This user will only have access to SQL data.

**Comment by cykie** [comment]
Hi v-robwhi,
Appreciate your prompt response.
I have set the execution policy to the right one and the ps1 file could be ran.
However, it doesn't seem to work.
I still get a bunch of error messages. (Pretty much the same as the previous error messages. )

I have attached the log here again for your reference. Could there be any incorrect setup in my laptop?
I am totally lost. Kindly let me know what may be the issue so that I can fix in my laptop and continue.

Thank you again!
[fraud_setup_log.txt](https://github.com/Microsoft/r-server-fraud-detection/files/1846096/fraud_setup_log.txt)

@v-robwhi

**Comment by v-robwhi** [comment]
for some reason the SQL Server Powershell Module is not installing correctly on your machine , can you try in stalling that prior to running the set up? Instructions are here https://docs.microsoft.com/en-us/sql/powershell/download-sql-server-ps-module

**Comment by cykie** [comment]
Hi v-robwhi,
Thanks for your suggestions!
I have actually install the SQL Server Powershell Module successfully on my laptop. And also installed some other feature package for SQL Server to solve the error message:
 ### "Invoke-Sqlcmd : The term 'Invoke-Sqlcmd' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again."


However, I am still not able to run the SetupVM successfully. 

So may I ask if there's an alternative way for me to execute the code separately? 
What is the purpose or steps that the SetupVM is going to accomplish. By understanding this, is there any code in the solution folders for me the execute the steps one by one to get the same results from running the Setup VM?

Thank you! (Sorry to disturb you again and again. But I hope I could really run this template successfully and get a good understanding of it. Thanks!!)

**Comment by v-robwhi** [comment]
I want to help you get this correct, I want to learn what issues you are having so I can get the setup correct. 
I have been making updates to the code as we go along , but not sure if you have received the updates. 
There is a new Setup file FraudSetup.ps1 that you can use. But you should also Delete the contents of c:\Solutions\. This will allow the new files to be cloned. If you could run the new setup and send me the Fraud_Setup_Log from c:tmp that would be great 

Bob

**Comment by cykie** [comment]
Hi Bob,
Thank you!
I have followed what you have told me to delete the solutions and re-run the new FraudSetup.ps1.
So here's the new log.
Basically, the main issue is the Invoke-Sqlcmd is not recognized. 

I am attaching the log here for your reference. Kindly let me know if there's any action needs to be done at my end. Thank you!
[fraud_setup_log.txt](https://github.com/Microsoft/r-server-fraud-detection/files/1858822/fraud_setup_log.txt)


Allison

**Comment by v-robwhi** [comment]
I see , there are a few other things it is not seeing also.  Try this, open a powershell script as an admin. CD to 'c:\Solutions\Fraud\Resources\ActionScripts' then run the command  '.\FraudSetup.ps1'.

What OS are you running , and which version of SQL?

Bob

**Comment by cykie** [comment]
Hi Bob,
I have tried to run the FraudSetup.ps1 under 'c:\Solutions\Fraud\Resources\ActionScripts' . It's not successful. Same error message pops up again. Here's the log. 
[fraud_setup_log.txt](https://github.com/Microsoft/r-server-fraud-detection/files/1870580/fraud_setup_log.txt)

my os: Windows 10 Pro
SQL:  SQL Server 2017

Thank you!
Allison

**Comment by v-robwhi** [comment]
Allison , can you contact me directly ,v-robwhi@microsoft.com , I would like to see your build out 

Bob
