### ISSUE TITLE
merge procedure

### ISSUE THREAD

**Issue by jusiahk** [Microsoft/r-server-fraud-detection#12]
Stuck on the merge procedure transactiondate/time tends to run out of range or fails to convert from varchar to datetime

**Comment by TheBharath** [comment]
Just to confirm you are running this offline. Can you provide information if you are using SQL Server 2016 or SQL Server 2016

**Comment by TheBharath** [comment]
Thanks. Please paste the line and the output that you got so that I can validate and respond.

**Comment by jusiahk** [comment]
EXEC MergeAcctInfo 'Untagged_Transactions'

Msg 208, Level 16, State 1, Line 4
Invalid object name 'Untagged_Transactions'.

(0 rows affected)

And am having alot of invalid object name yet havenot changed naming at all
if you execute the first three procedures.If you havea different link thats
fine please send it to me i fork it out thanks.


*Jusiah Noah Abel*
Data Analyst /Machine learning Engineer
Jusiahk@gmail.com/Jusiahk@outlook.com
M:+256772808236/256752609022
Xente.co Ntinda

***********The hottest place in hell is kept for those who remain silent in
times of trouble.**********
