### ISSUE TITLE
* Install failing at Step 4 *

### ISSUE THREAD

**Issue by Digitalborg** [microsoft/r-server-fraud-detection#13]
Greetings.
I am attempting to install this r-example on a Windows 10 Machine (Surface Studio 2) running SQL 2017 Dev edition.

I have installed VS2015 with R Tools.  I am running the modeling_main.r script from inside VS <Control-Enter>.  

The script stops at the same place, every time I have tried.  Below is the screen error messages:

Error in rxCompleteClusterJob(hpcServerJob, consoleOutput, autoCleanup) : 
  No results available - final job state: failed
[1] "Step 4: Training, Scoring and Evaluating."
Error in .nextMethod(.Object = .Object, ... = ...) : 
  object 'column_info' not found
[1] TRUE
Warning message:
In .local(src, ...) :
 The datasource is not open yet.

Any assistance would be appreciated.   I did edit Step 1 with the ServerName and security creds.  That is the only items I have changed.  Would the "R" issue of having spaces in the working directory name account for this?  Before I changed ANYTHING, I would like to hear from someone on here.

Thanks.

**Comment by jeroenterheerdt** [comment]
Hi @Digitalborg please try without any spaces in the working directory.

**Comment by jeroenterheerdt** [comment]
Closed because of inactivity.
