### ISSUE TITLE
Don't Understand Code Output

### ISSUE THREAD

**Issue by Eezzeldin** [microsoft/r-server-fraud-detection#14]
colnames(perf.df) = c('ADR','PCT NF Acct','Dol Frd', 'Dol NF', 'VDR', 'Acct FP(recontact period)', 'PCT Frd', 'PCT NF','AFPR','TFPR' )

What do these columns name Acrynoms stand for? i.e What is PCT NF Acct?

**Comment by jeroenterheerdt** [comment]
which part of the code are you running where you get this output?

**Comment by Eezzeldin** [comment]
[fraudTemplateUtil.zip](https://github.com/microsoft/r-server-fraud-detection/files/3193211/fraudTemplateUtil.zip)

**Comment by jeroenterheerdt** [comment]
The acronyms are defined in the code - I admit, they are all over the place. I will add these in.

```
ADR = Fraud Account Detection Rate
PCT NF Acct = Percentage on account level classified as Non-Fraud.
Dol Frd = Dollar amount Fraud
Dol NF = Dollar amount Non-Fraud
VDR = Value detection rate. The percentage of values saved
Acct FP(recontact period) = False positives for Account
PCT Frd = Percentage classified as Fraud
PCT NF = Percentage classified as Non-Fraud
AFPR = Account-level false positive ratio
TFPR = Transaction level false positive ratio
```

**Comment by Eezzeldin** [comment]
@jeroenterheerdt   would you confirm the below assumption please?

Transaction Metrics
=============
VDR     = Value detection rate. The percentage of values saved
TFPR    = Transaction level false positive ratio
Dol Frd = Dollar amount Fraud
Dol NF  = Dollar amount Non-Fraud
PCT Frd = Percentage classified as Fraud
PCT NF  = Percentage classified as Non-Fraud

Account Metrics
===========
ADR                       = Fraud Account Detection Rate
PCT NF Acct               = Percentage on account level classified as Non-Fraud.
Acct FP(recontact period) = False positives for Account
AFPR                      = Account-level false positive ratio

**Comment by Eezzeldin** [comment]
What is the difference between "Acct FP(recontact period)" Vs. "AFPR" ?

**Comment by jeroenterheerdt** [comment]
One is a ratio (AFPR) and the other is the absolute number.

**Comment by Eezzeldin** [comment]
In this R code file I found presented by jspoelstra* it has a function called "evaluatePerf" which include a modification of the VDR score based on "Delay.Range". I am very interested on this "Delay" metric and would love for it to be included in the body code here for getting VDR. Any chance you would consider adding this Delay metric to this source code?!

*the head of data science in the Microsoft team responsible for the Fraud Detectoin unit. 
https://gist.github.com/jspoelstra/9577c07d3c9d1087072b87051abd3c59
[fraudperf.zip](https://github.com/microsoft/r-server-fraud-detection/files/3263083/fraudperf.zip)

**Comment by jeroenterheerdt** [comment]
@Eezzeldin that's the beauty of open source - feel free to make the required / suggested modifications to this repository and send a PR (Pull Request). thanks.
