### ISSUE TITLE
SQL 2017 error

### ISSUE THREAD

**Issue by maccotto** [Microsoft/r-server-fraud-detection#7]
Hi, i install demo in SQL Server 2017 RTM and recive this error when execute TrainModelR in setup

STDOUT message(s) from external script: 
======  SQL2017  ( process  1 ) has started run at  2017-11-16 10:06:57.11  ====== 
 
The file or directory 'work\sample-ds1.xdf' cannot be found. 
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  The file or directory 'work\sample-ds1.xdf' cannot be found. 
Calls: source ... tryCatch -> tryCatchList -> tryCatchOne -> doTryCatch -> .Call 
Execution halted

**Comment by AlexanderTodorovic** [comment]
This error is also thrown when your data set is empty. Please verify your data set is not empty.
e.g. 
sampleDataQuery <- "SELECT a FROM mytable where a = 2"
inDataSource <- RxSqlServerData(sqlQuery = sampleDataQuery, connectionString = connStr)
rxGetInfo(data=inDataSource, getVarInfo = TRUE, computeInfo = TRUE)

So if the SELECT statement does not return data you'll get the same error message when you call a rx() function.
